name: Robot Update

on:
  workflow_dispatch: 
  # schedule:
  #   - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5 
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser requests deep-translator

      - name: Run News Robot
        run: python fetch_news.py

      - name: Commit and Push
        run: |
          git config --global user.name "Robot"
          git config --global user.email "robot@onimugen.com"
          git add data_gaming.json
          git commit -m "Robot: Fresh news batch [$(date)]" || exit 0
          git push
